services:
  - type: web
    name: fintech-backend
    env: node
    repo: https://github.com/VINANTH-H/Invenctio
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

